CREATE DATABASE bopIt_db;

USE bopIt_db;

CREATE TABLE baby 
(
    id INT NOT NULL AUTO_INCREMENT,
    birthYear VARCHAR(225) NOT NULL,
    gender VARCHAR(225) NOT NULL,
    origin VARCHAR(225) NOT NULL,
    name VARCHAR(225) NOT NULL,
    popularity INT(128) NOT NULL,
    value INT(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pet
(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(225) NOT NULL,
    PRIMARY KEY (id)
);